sudo: required
dist: trusty

language: node_js

node_js:
  - '10'

matrix:
  include:
    - os: osx
    - os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libgnome-keyring-dev
      - rpm
      - bsdtar

cache:
  directories:
  - $HOME/.electron

install:
  - npm install -g npm

before_script:
  - export TRAVIS=1
  - npm ci
  - npm run lint

script:
  - npm run build
  - npm test

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+.*/"
